version: '3.9'
services:
# hosting with apache server
  apache:
    image: httpd:latest
    container_name: cloud-resume-challenge-website-apache
    ports:
    - '8082:80'
    volumes:
    - '.:/usr/local/apache2/htdocs'
    healthcheck: 
      test: [ "CMD", "curl", "--fail", "http://localhost" ]
      interval: "30s"
      timeout: "5s"
      retries: 3
# hosting with nginx server
  client:
      image: nginx
      container_name: cloud-resume-challenge-website-nginx
      ports:
          - 8081:80
      volumes:
          - .:/usr/share/nginx/html
      healthcheck: 
        test: [ "CMD", "curl", "--fail", "http://localhost" ]
        interval: "30s"
        timeout: "5s"
        retries: 3