name: Deployment - terraform apply

on:
  workflow_dispatch:
    inputs:
        action_type:
            description: "Type of action you want to take (i.e. 'build' or 'destroy')"
            required: true

env:
   AWS_REGION: ap-southeast-2
   IAM_ROLE: "arn:aws:iam::663790350014:role/GitHubAction-AssumeRoleWithAction"
   TF_VERSION: 1.3.7
permissions: 
   id-token: write
   contents: read

jobs:
  tf-aws-cloud-resume-challenge-deploy:
    name: 'tf-aws-cloud-resume-challenge-deploy'
    runs-on: ubuntu-latest
    if: inputs.action_type == 'build'
    steps:
      - name: Check out this repository
        uses: actions/checkout@v3

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/setup-node@v3
        with:
          node-version: latest
  
      - run: npm i dotenv

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: false
      
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        continue-on-error: false
      
      - run: terraform output > .env

      - name: Overwrite Existing js File with New API 
        run: aws s3 cp js/main.js s3://tf-aws-jchung-cloud-resume-site-bucket/js/main.js
      
      - run: node js/main.js
  
  tf-aws-cloud-resume-challenge-destroy:
    name: 'tf-aws-cloud-resume-challenge-destroy'
    runs-on: ubuntu-latest
    if: inputs.action_type == 'destroy'
    steps:
      - name: Check out this repository
        uses: actions/checkout@v3

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: false
      
      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
        continue-on-error: false

