name: Deployment - terraform apply

on:
  workflow_dispatch:
    inputs:
      structure_type:
        description: "Part of structure you want to build/destroy (i.e. 'frontend' or 'backend')"
        type: choice
        required: true
        options:
          - backend
          - frontend
      action_type:
          description: "Type of action you want to take (i.e. 'build' or 'destroy')"
          type: choice
          required: true
          options:
            - build
            - destroy

env:
   AWS_REGION: ap-southeast-2
   IAM_ROLE: "arn:aws:iam::663790350014:role/GitHubAction-AssumeRoleWithAction"
   TF_VERSION: 1.3.7
permissions: 
   id-token: write
   contents: read

jobs:
  tf-aws-cloud-resume-challenge-build:
    name: 'tf-aws-cloud-resume-challenge-build'
    runs-on: ubuntu-latest
    if: inputs.action_type == 'build'
    steps:
      - name: Check out this repository
        uses: actions/checkout@v3

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v2

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'
      
      - name: Install boto3
        run: pip install --upgrade pip boto3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -target=module.${{ inputs.structure_type }}
        continue-on-error: false
      
      - name: Terraform Apply
        id: apply
        run: terraform apply -target=module.${{ inputs.structure_type }} -auto-approve
        continue-on-error: false
      
      - name: Run Unit Tests
        run: python3 -m unittest tests/test_${{ inputs.structure_type }}.py
              
  tf-aws-cloud-resume-challenge-destroy:
    name: 'tf-aws-cloud-resume-challenge-destroy'
    runs-on: ubuntu-latest
    if: inputs.action_type == 'destroy'
    steps:
      - name: Check out this repository
        uses: actions/checkout@v3

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -target=module.${{ inputs.structure_type }}
        continue-on-error: false
      
      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -target=module.${{ inputs.structure_type }} -auto-approve
        continue-on-error: false