name: Deployment - terraform test

on:
  pull_request:

env:
   AWS_REGION: ap-southeast-2
   IAM_ROLE: "arn:aws:iam::663790350014:role/GitHubAction-AssumeRoleWithAction"
   TF_VERSION: 1.3.7
permissions: 
   id-token: write
   contents: read

jobs:
  tf-aws-cloud-resume-challenge-test:
    name: 'tf-aws-cloud-resume-challenge-test'
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repository
        uses: actions/checkout@v3

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v2

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'
      
      - name: Install boto3
        run: pip install --upgrade pip boto3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan 
        id: plan
        run: terraform plan 
        continue-on-error: false

      
    
